spin_manifest_version = 2

[application]
name = "hello-replicated"
version = "0.1.1"
authors = ["Chuck D'Antonio <chuck@crdant.io>"]
description = "Exmaple application for running WASM on Replicated Embedded Cluster"

[[trigger.http]]
route = "/..."
component = "hello-replicated"

[component.hello-replicated]
source = "main.wasm"
allowed_outbound_hosts = []
[component.hello-replicated.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
